import { useState } from 'react'

import Head from 'next/head'

import Content from '@/components/Content'
import Layout from '@/components/Layout'
import Tabs from '@/components/Tabs'

import { SearchProvider } from '@/contexts/SearchContext'

export default function Home() {
  const [searchQuery, setSearchQuery] = useState<string>('')

  const [activeTab, setActiveTab] = useState<number>(0)

  const tabOptions = [
    {
      key: '',
      label: 'Live',
    },
    {
      key: 'business',
      label: 'Business',
    },
    { key: 'science', label: 'Science' },
    { key: 'health', label: 'Health' },
    { key: 'sports', label: 'Sports' },
    { key: 'technology', label: 'Technology' },
    {
      key: 'entertainment',
      label: 'Entertainment',
    },
  ]

  return (
    <>
      <Head>
        <title>News Aggregator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchProvider>
        <Layout>
          <Tabs
            tabs={tabOptions.map((item, index) => {
              return {
                key: item.key,
                label: item.label,
                component: (
                  <Content
                    key={item.key}
                    category={item.key}
                    isActive={activeTab === index}
                  />
                ),
              }
            })}
            onChange={(tabKey) => setActiveTab(tabKey)}
          />
        </Layout>
      </SearchProvider>
    </>
  )
}
